### ISSUE TITLE
[Feature request] Compiled copy of auspice bundle

### ISSUE THREAD

**Issue by acx01b** [nextstrain/auspice#1031]
@jameshadfield Hi, would you have a copy of auspice.bundle.js and auspice.chunk.1,2,4.bundle.js that will work when copied on my website directory ? It is too platform dependent and time consuming to recompile everything and I guess many people don't need it. Simply copying the files I could make it work yesterday (just creating the same directories as on nextstrain.org then replacing "charon/getDataset" by "charon/getDataset.json" in auspice.bundle.js) **but it doesn't anymore** I have no idea why (and the minified files + webpack weird behavior with debugger don't help to understand where it is failing) 

I need such a distinct copy to display ncov's getDataset.json where I changed/renamed the clades. My idea is that every country wants to have specific clades chosen such that describing the epidemilogy is easier (in France we have two subtrees of the Italian-European tree, originating in two different french cities)

**Comment by jameshadfield** [comment]
I'm not sure what exactly you're trying to do, but if you really want the transpiled auspice code you can access it via https://nextstrain.org/dist/auspice.bundle.js etc. This is hard to debug due to the minification steps when shipping production bundles. I recommend installing auspice locally and generating this via `auspice build`. 

If you want auspice to make a call to a single JSON rather than using the APIs (i.e. run without a server) then you can try building auspice with the undocumented [extension[(https://nextstrain.github.io/auspice/customise-client/api) `hardcodedDataPaths` (see https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L38-L66, there are no docs). This may need some debugging, as I haven't used it for quite a while, but it's how the (serverless) https://blab.github.io/ZEBOV/ works.

**Comment by acx01b** [comment]
Tks, I could make it work by deleting and recreating everything, just copying 

/charon/getDataset?prefix=/ncov 
/dist/auspice.bundle.js
/dist/auspice.chunk.1.bundle.js
/dist/auspice.chunk.2.bundle.js
/dist/auspice.chunk.4.bundle.js 

from nextstrain.org to the root of my website. There was probably a mix of version and cache conflits.

I could not make work https://blab.github.io/ZEBOV/ with ncov tree.

You can see there (if it is still working tomorrow^^) what I'm doing
http://babarlelephant.free-hoster.net/dist/ncov.html?c=clade_membership&i=1
There idea is that this renaming of the clades is valid from the french point of view, if you are from another country you will probably change and rename them, to make the epidemiology easier to describe.

**Comment by jameshadfield** [comment]
Ok. Auspice isn't currently designed for running statically (without a dynamic server to respond to `/charon` API calls), but this will hopefully be possible one day (issues welcome). Also, I highly recommend installing auspice and generating bundles yourself via `auspice build`, rather than copying prebuilt bundles from nextstrain.org.
