### ISSUE TITLE
Cannot change tree layout when animation is paused

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1047]
**Current / Expected Behavior**  
During animation we block the ability to toggle between tree layouts. However when an animation is paused, you should be able to change the tree layout but you cannot.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open e.g. https://nextstrain.org/zika, localhost:4000/zika
2. Start the animation.
3.  Pause the animation before it finished.
4. Try to change the tree layout (e.g. to radial). You can't. This is unintended.
5. Press "reset" (on the map) to reset the animation.
6. The tree layout buttons now work again.

**Possible solution**  
It will be related to us disabling the layout buttons during animation. This is intentional (however we could do a better job of indicating that they are disabled!). 

**Your environment: if running Nextstrain locally**  
Auspice v2.11.4

**Comment by mingir2** [comment]
@jameshadfield Toggling other options re-enables the layout toggle.

4. Change branch length from TIME to DIVERGENCE and vice versa.
5. Now the user can change layout without resetting the animation.

So it seems like the layout buttons aren't disabled, at least not completely.

**Comment by mingir2** [comment]
https://github.com/nextstrain/auspice/commit/86ef2f3d4f326707ecf514750a5d4757bc7883f3#diff-b9348df9e82661936e947d54ef9491a1R35

```js
const loopRunning = window.NEXTSTRAIN && window.NEXTSTRAIN.animationTickReference;
```

This line is preventing a user from changing layout if there is in the middle of an animation loop. With out this constraint, the layout can be changed in during the animation.

**Possible solution**
Allow user to change layout after the pause, but prevent the user from changing layout during the animation. 

The line I mentioned above is executed in render function, this results in the onClick functions to stay disabled because there wasn't any UI updates from pausing the animation for the ChooseLayout component. What I can do is defining a helper function to replace the anonymous onClicks functions that are currently in place. This will make sure the loopRunning constant is valid when the onClick event happens.
