### ISSUE TITLE
Add testing which simply loads datasets

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1048]
There are other PRs which are implementing more advanced E2E tests etc, however a complementary (and simpler) approach which would be _extremely_ valuable for Nextstrain is to load a number of URLs and check that they work*. Having this easily runnable on every PR would save a lot of time and help prevent bugs. 

[*] By "work" I mean that the app loads without errors. I'm not actually sure how to programmatically check this, perhaps checking for any `console.error` calls, or if any ErrorBoundaries are run (they could be made to always trigger a `console.error`)? 

**Examples**  
I imagine maintaining a (perhaps quite large) list of URLs such as
```
localhost:4000/ncov
localhost:4000/zika
localhost:4000/zika?legend=open&c=region&r=region&l=clock&m=div
```

**Comment by bcoe** [comment]
@jameshadfield I would be happy to help with this, you're picturing a script that basically:

1. `npm i`.
2. `npm run get-data`
3. `npm run get-narratives`
4. smoke tests against a list of URLs?

Would you be open to doing this in a GitHub action? I think actions could be a great way to write these targeted little checks, rather than shoe horning it into the existing Travis config.
