### ISSUE TITLE
Allow JSONs to define language for auspice

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1049]
Auspice 2.12 allows one to set the language via a URL query, e.g. `?lang=ja` is Japanese (see the dropdown at the bottom of the sidebar for all the available languages). This is detailed [here](https://nextstrain.github.io/auspice/advanced-functionality/view-settings#url-query-options) in the docs.

This should also be settable via the `display_defaults` in the JSON (see [docs](https://nextstrain.github.io/auspice/advanced-functionality/view-settings#dataset-json-configurable-defaults)). For instance, a JSON with 
```json
"display_defaults": {
    "language": "ja"
}
```
Should display auspice in Japanese. This can be overridden by a URL query, and should be removed from the query and an error printed to the console if the language does not exist in auspice.

**Comment by charlie-jones** [comment]
Hi, I can do a PR for this. My proposal is to use meta.display_defaults from recomputeReduxState.js to set the language in const defaults = {} from src/reducers/general.js.

**Comment by jameshadfield** [comment]
That would be great!

**Comment by charlie-jones** [comment]
Hey again -- so sorry for the delay. My steps for this were to import the JSON directly to general.js; that way, a function there can easily parse it to get a newly added language parameter (similarly to how recomputeReduxState.js works). I'm having trouble though finding the display_defaults data json (in augur - schema-export-v2.json) info that recomputeReduxState.js uses. Anyone know how to import json similarly for general.js? Thanks.

**Comment by charlie-jones** [comment]
I'm going to move on from this issue. For others reviewing this issue -- feel free to refer to the steps above for inspiration and please try making a PR.

**Comment by eharkins** [comment]
Hi @charlie-jones, thanks for working on this! I think I would start in the same place as you, i.e. 
> use meta.display_defaults from recomputeReduxState.js to set the language

However, I'm not sure I understand the following:
> My steps for this were to import the JSON directly to general.js; that way, a function there can easily parse it to get a newly added language parameter (similarly to how recomputeReduxState.js works)

I think instead of importing the JSON directly into the redux reducer, you should be able to make use of a pattern similar to existing ones for setting display defaults in the function `modifyStateViaMetadata`  in recomputeReduxState.js with the difference here being that most of those defaults are set on state.controls where as the language setting applies to state.general. 

When a new dataset is loaded, here is (my understanding of) how defaults are set in the redux state:
1. [loadData](https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L243) is called
2. loadData creates a new state from the JSON in [createStateFromQueryOrJSONs in actions/recomputeReduxState.js](https://github.com/nextstrain/auspice/blob/master/src/actions/recomputeReduxState.js#L662).
3. This newly created state from the JSON gets [dispatched in a CLEAN_START action](https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L177).
4. This action is handled by each reducer according to what values are contained in that new state and need to get set in the redux state. 

So I think the key here is  figuring out how to translate this pattern from the version that works for the various pieces of state.controls that are set according to display defaults into a version that will work for the language piece of state.general.


> I'm having trouble though finding the display_defaults data json (in augur - schema-export-v2.json) info that recomputeReduxState.js uses.

A good example dataset you might be able to use to test a fix to this issue exists [here in this repo](https://github.com/nextstrain/auspice/blob/master/examples/minimal_v2.json#L37).

Hope this helps!

**Comment by charlie-jones** [comment]
Hi @eharkins, thank you for your help! I'm sorry I didn't work on this for a while, but I truly appreciate your help/advice. I implemented it and then made a pull request (https://github.com/nextstrain/auspice/pull/1211), but I haven't tested the code on the test JSON because I couldn't figure out how to run it. I'm hoping the code helps, and if I find out how to run the test JSON, I can work on it more next weekend.
