### ISSUE TITLE
Enable a narrative to source multiple builds

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/auspice#1050]
**Context**  
We publish weekly situation reports using narratives on the spread of COVID-19. These situation reports are broken into sections by world region. Latest report for example: https://nextstrain.org/narratives/ncov/sit-rep/2020-04-03

Currently, narratives can only source one dataset. When there was only one global `ncov` build, this wasn't a problem. Now that we have multiple subsampled builds (`ncov/global`, `ncov/europe`, `ncov/africa`...) using only one of these builds for the situation reports greatly limits the data we can cover.

**Description**   
We'd like to upgrade the narratives functionality, so it can source multiple datasets within a single narrative. For example, one slide could show the `ncov/global` build and the next slide could show the `ncov/north-american` build.

**Possible solution**   
There's been some limited discussion about the problem at issue: https://github.com/nextstrain/auspice/issues/890

**Comment by jameshadfield** [comment]
This would be wonderful.

Currently the architecture of auspice is designed around loading a single dataset ([code which fetches the JSONs here](https://github.com/nextstrain/auspice/blob/master/src/actions/loadData.js#L124-L188)). This dataset JSON essentially generates _most_ of the redux state needed to display that dataset, via [createStateFromQueryOrJSONs](https://github.com/nextstrain/auspice/blob/4402d587a4102950ba70bb2dead6a84a5a200db7/src/actions/recomputeReduxState.js#L652). 

(The way narratives work is that they then use URL queries to modify this redux state when you move between slides, thus affecting how the data should be presented. This is via  `createStateFromQueryOrJSONs`.) 

To allow multiple datasets the redux state (via `createStateFromQueryOrJSONs`) will have to be re-created from the "new" dataset JSON when moving to that page in the narrative. In theory this isn't too bad, but there will be lots and lots of little bugs (I explored this a little bit when first building narratives, since I always wanted it, but hasn't been high priority until now). Since fetching JSONs is slow, any solution should pre-fetch the required JSONs for the narrative & store them in a redux cache or similar.

**Comment by salvatore-fxpig** [comment]
Opened a WIP here https://github.com/nextstrain/auspice/pull/1071 but needs help for comments, test cases, debugging

**Comment by jameshadfield** [comment]
Leaving a summary of a comment in #1071 here for posterity also:

I've made a test narrative to demonstrate the functionality this issue is asking for: [markdown here](https://github.com/nextstrain/narratives/blob/master/test_multiple-datasets.md) and visible on nextstrain.org [here](https://nextstrain.org/narratives/test/multiple-datasets). This is a simple 3-slide narrative which should change from the mumps dataset to the zika dataset, but it currently does not. To run locally in auspice, you should run `npm run get-data` to get the dataset JSONs from the S3 bucket and then `npm run get-narratives` to collect the narrative markdown files, including the test one linked to above. You can then view it via `auspice develop` and going to http://localhost:4000/narratives/test/multiple-datasets. (Note that running it on current master causes no crashes, but the dataset doesn't change.)

**Comment by salvatore-fxpig** [comment]
Posted an update in the PR about 10 days ago, I guess you guys are super busy these days but just wanted to make sure it does not end up flying under the radar @jameshadfield .

**Comment by jameshadfield** [comment]
This looks pretty good! I know @eharkins has tested this a bit, so look out for a review from him in the coming days 👍

**Comment by eharkins** [comment]
Closed by #1164
