### ISSUE TITLE
Keep Recent Filter Options at Top of Page

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#1056]
**Context**  
Currently, to use filters one must scroll up and down past the tree, map, entropy, and description to find them listed, then scroll back up to the tree to see the effect. Especially if there's a long description and many filters, this can be very tiresome when trying to visualise the tree by putting on/off multiple filters. (See https://nextstrain.org/ncov)

Often only handful of filters are used, and having a selection 'stay' at the top of the page, where they show when they are currently applied, so that they could easily be re-applied, would be really helpful for toggling on/off.

**Description**   
Some kind of storage of the last ~5 filters used. These would be displayed at the top of the page (whether on or off). At the moment, turning off makes them disappear completely. In the new method, they would somehow stay at the top, but appear 'off'. This way they could easily be re-selected. If more than 5 are used, only the most recent 5 would be shown at the top (whether on or off, currently). 

**Examples**  
Current view: 
![image](https://user-images.githubusercontent.com/14290674/79047023-87ef0480-7c14-11ea-8cf8-7330f3133a37.png)

**Possible solution**   
![suggestionFilters](https://user-images.githubusercontent.com/14290674/79047165-4d399c00-7c15-11ea-8764-b4a531f6701d.png)

**Comment by trvrb** [comment]
Thanks for filing this Emma. I would suggest a slightly different UI. After clicking on a filter on the bottom of the page it would appear at the top as it currently does. However, you can now click on the words "New (30)" to have this filter be de-selected with the following UI:

<img width="935" alt="recent-v2" src="https://user-images.githubusercontent.com/1176109/79048231-784dcc80-7bd0-11ea-8477-71977b436af1.png">

Where that filter gets a gray box rather than a blue box. It can be toggled on-and-off by clicking on the name. Just as it currently stands, the filter can be dismissed by clicking the x. Clicking the x will dismiss both an inactive (in gray box) or an active filter (in blue box).

This design would work with any number of filters added to the top of the page (rather than the most recent 5) and would make a direct mouse-in-place toggle on/off rather than having to move the mouse to click a recent filter and then move back to turn it off again.

**Comment by emmahodcroft** [comment]
Ah, I misunderstood the original - yes, this sounds very good!

**Comment by jameshadfield** [comment]
Sounds good to me. To indicate to people that this functionality exists there should be (at the least) a on-hover info box indicating that if you click on the filter (not the "x") then it'll toggle off but remain in the header. May be other UI ways to accomplish this also.

**Comment by trvrb** [comment]
This was accomplished and we now have toggleable filters.
