### ISSUE TITLE
git-lfs has to be installed to clone or merge from repo

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#1089]
**Current Behavior**
When cloning the auspice repository (or trying to merge into an existing repo), I get the following error:

```bash
$ git clone https://github.com/nextstrain/auspice
Cloning into 'auspice'...
remote: Enumerating objects: 27630, done.
remote: Total 27630 (delta 0), reused 0 (delta 0), pack-reused 27630
Receiving objects: 100% (27630/27630), 13.95 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (20366/20366), done.
git-lfs smudge -- 'test/integration/__image_snapshots__/Color-by:author-snap.png': git-lfs: command not found
error: external filter git-lfs smudge -- %f failed -1
error: external filter git-lfs smudge -- %f failed
fatal: test/integration/__image_snapshots__/Color-by:author-snap.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Expected behavior**  

[According to the DEV_DOCS](https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#git-lfs), I should not need to have git-lfs installed unless I am running tests.

**Possible solution**

I think the [.gitattributes file](https://github.com/nextstrain/auspice/blob/0d2eaf468df1466c949d6d3cb2333c542d9af537/.gitattributes#L1) need to be modified somehow to prevent lfs from being required on clone/merge. If that isn't possible, it might be better to disable the LFS filter for now.

**Environment**

```
$ git --version
git version 2.10.0
```

**Comment by jameshadfield** [comment]
Thanks for the detailed bug report here John. I was under the impression that this wouldn't happen -- without `git-lfs` installed the `png` files would simply be small text pointers rather than the actual file but this doesn't seem to be the case. Interestingly, certain jobs in the GitHub CI checkout the repo without `lfs` and are working fine. @eharkins if you haven't already installed `git-lfs` could you see if you can reproduce this?

**Comment by tsibley** [comment]
I believe that `git lfs` is, correctly, not required. For example, I can clone the repo freshly without issue and without `git lfs` installed.

Looking more closely at the error message, I believe the issue is that the `lfs` filter, diff, and merge drivers are _configured_ in @huddlej's git config but `git lfs` isn't actually installed anymore. e.g. a previous installation of `git lfs` was incompletely uninstalled.

**Comment by huddlej** [comment]
@tsibley's conclusion is correct here. Removing my old LFS settings from `.gitconfig` fixed this problem. Thanks all and sorry for the false alarm!
