### ISSUE TITLE
Ebola dataset broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#115]
Possible causes: 
* tree time confidence intervals mis-parsed in Auspice
* globals are specific to zika

**Comment by rneher** [comment]
not sure what exactly is the issue, but I suspect the you are referring o confidence intervals not overlapping the actual tree node. this can occur in data sets like ebola with very many zero-length branches. in such a case, the most-likely configuration is a very atypical one. (example: the 5-95% confidence of a draw from an exponential distribution does not contain the most likely values). This should be fixed by assigning the marginal ml positions rather than the global ml positions.

**Comment by jameshadfield** [comment]
Thanks @rneher 
I'll look into this ASAP (I think there are more issues than just the CIs)

Current appearance of the ebola tree: 
![image](https://cloud.githubusercontent.com/assets/8350992/22399660/7b8f6d68-e556-11e6-9706-41b84ab37272.png)

Timelines of dataset change (c. 6s):
![image](https://cloud.githubusercontent.com/assets/8350992/22399664/a2952920-e556-11e6-8039-512bba629715.png)

**Comment by rneher** [comment]
set this to false:

https://github.com/nextstrain/auspice/blob/master/src/components/tree/treeView.js#L194

the confidence stuff was just a first shot, prob shouldn't have made its way into master yet.

**Comment by jameshadfield** [comment]
Closed in PR #156
