### ISSUE TITLE
Branch Colors Don't Seem to Change in Narrative

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#1168]
**Current Behavior**  
When changing the color-by in a narrative, the branches remain the same as the original colouring of the tree when the narrative is loaded.

Here is a narrative loaded up with 'clades' colouring - but then it switches to 'division' and 'nucleotide' colouring - however the branches remain the same colour.

![branch_color_narratives](https://user-images.githubusercontent.com/14290674/84592530-9fca4b00-ae46-11ea-950d-9e4b7c4946d8.gif)

Here, I loaded near the end when colouring is by 'nucleotide' - as we go backwards we can see the nucleotide colouring remains on the branches.
![branch_color_narratives2](https://user-images.githubusercontent.com/14290674/84592605-297a1880-ae47-11ea-84aa-aeefb5c309f7.gif)

**Expected behavior**  
The branch colours should change along with the tip colours when changing color-by in the narratives.

**How to reproduce**  
Can be reproduced with any narrative where color-by changes. Can be see (not super obviously, but it's there) in slides 4 & 5 of this narrative:
https://nextstrain.org/groups/swiss/narratives/sit-rep-2020-06-07?n=4

**Your environment:**  
Windows 10, running in WSL, viewing auspice (just pulled today) locally. But also in the online version of auspice (see above link).

**Comment by emmahodcroft** [comment]
Oh - this is weird. If I mouse over branches I can often restore what colour they are supposed to have. It's like colouring-in! 
![branch_color_narratives_recolor](https://user-images.githubusercontent.com/14290674/84592664-a73e2400-ae47-11ea-8570-c7cedb60abe4.gif)

**Comment by jameshadfield** [comment]
Thanks @emmahodcroft -- this is indeed a bug, and one we've had before and I thought fixed 😦. 

Thie bug (as with a lot of bugs in narratives) is caused when the d3 tree rerendering doesn't use the newly computed colours, usually because multiple d3 updates happen at once. The branch-hover action "fixes things" because this triggers a d3 to redraw the branch using the appropriate colour.

**Comment by rneher** [comment]
this is probably connected to this slightly crazy internal diffing that we introduced ages ago in phyloTree, right?
https://github.com/nextstrain/auspice/blob/master/src/components/tree/phyloTree/change.js

At some point we might want to consider reorganizing this beast...

**Comment by jameshadfield** [comment]
Yes, this bug will probably be fixed by some modifications to `change()`, but that function exists to solve a lot of problems with the different underlying approaches of react & d3. These problems weren't too common when we were changing one piece of state at a time (e.g. via mouse clicks) but narratives, which change many pieces of state simultaneously, were unworkable. There was talk of using webGL to render the tree which would be another avenue to explore.

**Comment by emmahodcroft** [comment]
Thank you @jameshadfield !
