### ISSUE TITLE
Inconsistency between the count of data and unknown attributes

### ISSUE THREAD

**Issue by islekburak** [nextstrain/auspice#1173]
**Current Behavior**  
There will be inconsistency for the count of data information that auspice demonstrate at the bottom of the page, when we used "?" in a column of metadata for unknown demes instead of Nan. 

**Expected behavior**  
Normally augur trait module suggests to use "?" for unknown attributes to make analysis, but at the end of the analysis, when we visualize the final .json file with auspice, we expect that the counts of data represented in paranthesis at the bottom of the page (by filtering options, i.e filter by city -> istanbul (5)) should be the same with the counts of data originated from selected deme (i.e Istanbul)

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Run augur's modules (refine)
2. Run augur's traits module and export data as .json file
3. Get the final .json file to visualize in auspice
4. See the bottom of the webpage that auspice creates.
5. In filtering options by demes, in case of  we have "?" in metadata, we will see incosistency between the counts of data in real and auspice shows. 

**Possible solution**  
If we use Nan instead of "?" in metadata with augur traits module for unknown data, it works correctly. But it is not suggested and may give a false positive for unknown attributes. 

**My environment**  
 - Operating System: Linux Mint 19.2
 - Kernel: Linux 4.15.0-91-generic
 - Architecture: x86-64
 - Browser:  Google Chrome
 - Version (`augur 8.0.0`, `auspice 2.11.2`):  

**Additional context**  
Normally we have just 5 data from Istanbul but it looks like 77 in auspice, shown below.
![auspice](https://user-images.githubusercontent.com/48826672/84989846-f6889b00-b14c-11ea-9624-9ec6e7c748e9.jpg)

**Comment by emmahodcroft** [comment]
Hi @islekburak - thanks for reaching out! Are you performing a traits reconstruction on the location (city, I think)? If so, if you enter ? for missing information, this will be reconstructed - so any places that are missing a city, it will try to guess what city fits these sequences. Using NaN means these will not be reconstructed. Could that be what's happening here?

**Comment by jameshadfield** [comment]
We need to update [the augur docs](https://nextstrain-augur.readthedocs.io/en/stable/usage/cli/traits.html#what-about-missing-data) for this. I typically use an empty string for missing data, which will not be inferred by `augur traits`, but "NaN" seems like it also works :)

**Comment by emmahodcroft** [comment]
James, if I were to update this, is correct to say that `?` is inferred, but any other values are not? That we suggest using an empty space if you don't want a value to be inferred? Are `NA`, `unknown` etc still interpreted as separate values? I think we changed this, but can't quite remember...

**Comment by islekburak** [comment]
Thanks for your consideration.
@jameshadfield I believe that using "?" instead of empty strings, changes the predictions and estimations of augur traits module analysis. By the way using "?" as suggested in augur docs, will give us more reliable and confident results.
@emmahodcroft In this manner, the phylogenomic & time-resolved tree analysis would be considered as correct while using "?", but not in auspice part. In contrast, using empty strings for blanks or unknown demes will give us results with false positives in the analysis (augur traits module), but it will correct the "counts of data" problem in auspice part.
Thus, what would you recommend to make this analysis? Empty strings for blanks/unknown demes or "?" ? Which use is the correct one to get truthful data during analysis?
Or it might be helpful to update the piece of code for calculating "counts of data" (in auspice) represented in parenthesis, while using "?" in the analysis.

**Comment by emmahodcroft** [comment]
@islekburak , I'm not sure how using blank values will give you 'false positives' - but maybe I'm not understanding. In this, for the location data, from the sound of what you're doing, I'd suggest indeed leaving these locations blank rather than using `?`. I don't think you want to be trying to reconstruct the city that a sample comes from - this is unlikely to be very reliable for SARS-CoV-2 sequences. If you leave these blank, then you're accurately representing that you don't know the city these came from. We have plenty of sequences without location (sometimes even without division) information in the Nextstrain SARS-CoV-2 build.

The `?` used to infer the state of a trait always needs to be used carefully - as often there isn't enough data, not not enough signal in the tree, to reconstruct these confidently. If uncertain, I'd say it's always best to go with a blank entry, as then you know you are accurately conveying the missing information!

I've updated the documentation that James linked above, though it'll take a little while before it shows up 'live'. However, this should help to make things clear for others! Thanks for alerting us to that!

**Comment by jameshadfield** [comment]
My understanding (from a few months back) is that
* `"?"` is inferred. I.e. a tip with `?` will be given a value (and associated confidences) in the resulting JSON.
* `""` (empty string) is ignored by `augur traits` -- i.e. a tip with this value will not be inferred, and it will not inform the ancestral node's inference. 
* Any other string is a valid value. This may not be true -- e.g. `"NaN"` or `"unknown"` might be treated as a special case.

But in light of these questions I think each case needs to be tested & documented.
