### ISSUE TITLE
Zoom into animation has broken

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#1191]
**Current Behavior**  
When zooming into a clade, the tree now snaps to the zoomed clade rather than doing a proper zoom animation. Interestingly, when "reset zoom" is run the zoom out animation occurs as intended. This bug in behavior can be ready seen in https://nextstrain.org/zika or https://nextstrain.org/groups/blab/sars-like-cov. I think it was missed in https://nextstrain.org/ncov/global, just because it's hard to see the animations in large trees due to lag.

**Expected behavior**  
When zooming into a clade, there should be animation going from original view to zoomed view.

**Comment by jameshadfield** [comment]
Good bug! We keep track of when the previous tree manipulation happened, and if it was within the last second then we don't transition (for performance reasons). This bug appears to be due to a branch-hover event being incorrectly counted as such a manipulation (wasn't the case in v2.4). If you hover on a branch for over a second before clicking you'll see it zooms as desired. Should have a fix us shortly.
