### ISSUE TITLE
Adding metadata should automatically filter the tree

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1242]
If metadata is dragged onto auspice, then we should filter the dataset to those samples included in the CSV/TSV file. 

As a shortcut: once #1293 has been closed, then adding a column to the CSV with the same value for all samples (e.g. `"additional": "yes"`) should allow one to filter the data by this trait.

**Comment by trvrb** [comment]
I'm not sure about this one actually. I'm picturing the scenario of dragging on a tsv with ~500 strain designating outbreak clusters onto the ~2000 tip SARS-CoV-2 tree. I don't want to clog up the top title area with 500 individual strain toggles. Or were you picturing some other UI here? Perhaps adding an additional "filter" that is `Drag-n-drop strains` or some such that is initially activated?

**Comment by emmahodcroft** [comment]
I'm not sure about this one either. If I've got datasets where I have extra meta I often drag this on 'straight away' so that it's there, but that may not necessarily mean I want to filter by it straight away - I'm often going to look at multiple things, many of which involve all the sequences - I just like to get 'set up' right from the start and then do all my 'looking'. But I accept this is just one use-case example, so if it's more common that people only drag the file on when they need it, I'll accept that!

However, I agree that it should be more easy to filter by the traits in the dragged-and-dropped file via once it's there!

**Comment by allenkj2** [comment]
I don't know if I would necessarily like them filtered either, the filtering is a little cumbersome because you can no longer see the nearby tips even when you zoom in all the way, so I end up removing the filters once I'm zoomed in so I can actually see the surrounding tips.

I would like it if those without the additional metadata would not show over top of the metadata colored ones - they are all gray, but the colored ones can get lost underneath the background. 
![image](https://user-images.githubusercontent.com/71853941/101804284-45910680-3ac6-11eb-860c-537006d6c550.png)

**Comment by jameshadfield** [comment]
Thanks for comments 💯 

> Perhaps adding an additional "filter" that is Drag-n-drop strains or some such that is initially activated?

This is along the lines of the UI I envisioned - adding a new metadata trait which one can filter on, and which is activated automatically when a file is dropped on. Feedback from @cassiawag was that it was that labs need to focus on a (often large) set of sequences and see them in context. Being able to quickly toggle on/off this filter is a nice way to achieve this (in my opinion!). #1241 is related, but needs a lot of thought to get right (and we may decide it's not the right approach). 

> the filtering is a little cumbersome because you can no longer see the nearby tips even when you zoom in all the way, so I end up removing the filters once I'm zoomed in so I can actually see the surrounding tips.

We attempted to remedy this by allowing filters to be quickly toggled on/off (via the "eye" icon next to the filter). Would be great to hear if this is a suitable solution here or if it's still lacking!

> they are all gray, but the colored ones can get lost underneath the background.

This is potentially quite hard to solve, but I think we all agree this isn't ideal. In the situation where some tips have no color-by information they would ideally be rendered _behind_ tips which do.

**Comment by cassiawag** [comment]
Thanks for this James! I agree with others in that I don't think it needs to _automatically_ be filtered to drag-n-drop metadata, but having a quick way to _choose_ to toggle on filtering to metadata would be awesome!

**Comment by allenkj2** [comment]
> We attempted to remedy this by allowing filters to be quickly toggled on/off (via the "eye" icon next to the filter). Would be great to hear if this is a suitable solution here or if it's still lacking!

Thank you for nicely pointing out that I didn't actually read all the documentation on the filtering, that is a really helpful feature. I don't see the "eye" icon next to the filter group - is it possible to turn all filters off/on in a similar manner? I often will have quite a few filters turned on and it would be nice to turn them off/on in one click instead of finding each one individually.

**Comment by cassiawag** [comment]
@allenkj2 The toggle filter on/off should show up above the tree: 
![eye_filter](https://user-images.githubusercontent.com/41387591/101947113-c8888e80-3ba4-11eb-893a-3288108d98bd.PNG)

**Comment by allenkj2** [comment]
@cassiawag That works individually, but if I have multiple sequences filtered there's not the 'eye' option over on the left nav. to inactive a group. 
![image](https://user-images.githubusercontent.com/71853941/101950783-b0b40900-3baa-11eb-9a80-21b432295c4f.png)

**Comment by cassiawag** [comment]
Yeah, there's not. I think you'd need to inactivate each individual filter setting with each eye icon.
