### ISSUE TITLE
Hide branch labels for inactive branches

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#1335]
**Context**  
Currently, branch labels are always drawn regardless of whether branches are active or inactive. In some ways this is helpful to always provide context like in the following:

https://nextstrain.org/ncov/global?f_clade_membership=20H/501Y.V2
<img width="1086" alt="tree" src="https://user-images.githubusercontent.com/1176109/114257028-ec50bb00-9971-11eb-8e6f-3282b0e1bb01.png">

However, in clock and scatterplot views it gets confusing really quickly which branch labels apply to which branches. See for example:
https://nextstrain.org/staging/ncov/global-with-dfreq?d=tree,frequencies&l=scatter&p=full&scatterY=logistic_growth
<img width="1086" alt="logistic" src="https://user-images.githubusercontent.com/1176109/114257047-0db1a700-9972-11eb-81bf-9ab053f5739e.png">

where it really looks like the subclade within 20H is actually 20J/501Y.V3.

**Description**   
I'd like branch labels to be hidden if the branch / node that they are attached to is hidden. I think this will generally result in less confusion.

**Comment by emmahodcroft** [comment]
I'd perhaps like this to be toggleable. I use the branch labels a lot when navigating the tree in various filtered & zoomed nodes, and it would be inconvenient if any level of hidden meant the branch label didn't show. Perhaps we can add a toggle under the branch-label drop-down saying 'show if branch hidden' which could turn to 'off' when switching to scatterplot mode? As I'd vote to keep it in tree mode - it's very useful.

**Comment by trvrb** [comment]
Interesting. This is a bit surprising to me. I think I'd almost always prefer for branch labels to be hidden when attached branches are hidden. For example, here's AA mutations for a subclade Delta filtered to samples from India as app currently works:

<img width="649" alt="filtered" src="https://user-images.githubusercontent.com/1176109/124400406-f404cf00-dcd6-11eb-8a8d-de5de4f63bc6.png">

I find it odd to have AA mutations for all these inactive branches. Close to text hovering in thin air for me.

I see what you mean about clade labels providing orientation, but this also looks slightly odd to me:

<img width="649" alt="clades" src="https://user-images.githubusercontent.com/1176109/124400457-68d80900-dcd7-11eb-9457-8c3ef01a0d88.png">

I'd expect 21B to not show up if 21B is not in the data at hand.

**Comment by emmahodcroft** [comment]
For me this is tied into the fact that it's not so easy to hit intermediate zoom levels when filtering, since all ancestral branches are 'minimized'. (So, if you have a couple of sequences that you want to look at with some neighbours, this is a practice of turning on/off filters while trying to hit the right intermediate zoom you're seeking.) For this, having branch labels even when minimized gives you some 'landmarks' to use to orient yourself on the tree.
I agree it isn't 100% canonical to have branch labels visible when the branch isn't, but until we've resolved making intermediate zoom easier with filters on, I'm loathe to make it more difficult!

**Comment by jameshadfield** [comment]
In order to test the behavior where branch labels are hidden we can use this review app: https://nextstrain-s-auspice-pr-r6szjr.herokuapp.com/ncov/open/global

**Comment by trvrb** [comment]
Thanks James. This is really helpful. I, of course, like this functionality. If you do something like filter to Alpha, Beta, Gamma and Delta you get shown just the branch labels that are relevant and can see that 20A and 20B are the immediate common ancestors to these clades. I find:

![hidden](https://user-images.githubusercontent.com/1176109/125009856-36e9de00-e01a-11eb-9351-23931baf7f44.png)

to be visually cleaner and I can parse what's going on better than:

![visible](https://user-images.githubusercontent.com/1176109/125009882-42d5a000-e01a-11eb-8e8b-0b2d9c093ed3.png)

Likewise, if I filter to just South Africa, it makes it clear that a number of clades aren't present:

![south-africa-hidden](https://user-images.githubusercontent.com/1176109/125009972-76b0c580-e01a-11eb-9b28-9dbec7e9336c.png)

Compared to:

![south-africa-visible](https://user-images.githubusercontent.com/1176109/125010038-96e08480-e01a-11eb-81df-0ada7a311cc4.png)

And of course, the original inclination or scatterplots like the above filtering to Alpha, Beta, Gamma, Delta gives a comparison of logistic growth rates that is parsable when filtered:

![logistic-growth-hidden](https://user-images.githubusercontent.com/1176109/125010321-2423d900-e01b-11eb-9238-d5b67ec8d6fa.png)

Compared to:

![logistic-growth-visible](https://user-images.githubusercontent.com/1176109/125010335-2b4ae700-e01b-11eb-9154-673a82bf1479.png)

which I have trouble visually parsing.

Emma, can you try out this PR and see how it feels for you? I'm very much in favor, but I think I don't fully understand your use case.

**Comment by emmahodcroft** [comment]
My main concern here was just navigating with filters on, particularly when you've selected a bunch of tips (so that the time it takes to turn them on/off is long enough that you can totally forget where you were aiming to click). I think the merging of #1371 and #1372 will make navigating & zooming a lot easier, so that this won't be such an issue anymore - you can easily make all the branch labels visible again with a click or two. If all these can get merged in together, I think all will be working well and looking good!
