### ISSUE TITLE
Support setting security HTTP headers

### ISSUE THREAD

**Issue by elliotkendall** [nextstrain/auspice#1480]
### Context
Currently Auspice doesn't provide a way to set common security-related HTTP headers that are recommended for contemporary web applications. Supporting these would improve security with little potential downside.

### Description
Provide a way to set security-related HTTP headers such as Strict-Transport-Security, X-Frame-Options, etc.

### Possible solution
It seems straightforward to implement a range of security headers in Express.js using the Helmet module: https://helmetjs.github.io/

Note that Helmet for Express.js should not be confused with the unrelated react-helmet module that Auspice already uses to manage the document head!

**Comment by jameshadfield** [comment]
Is this related to https://discussion.nextstrain.org/t/post-nextstrain-results-on-the-public-website-securely/1029 or coincidence?

**Comment by jameshadfield** [comment]
> When people ask for systems to allow inbound connections through our border firewall

Just want to clarify - are we talking about nextstrain.org URLs (i.e. hosted by us, served by github.com/nextstrain/nextstrain.org), or is the user running a auspice server locally to view datasets (I guess not, as that's localhost and thus http), or are they standing up their own server running auspice and sharing it (either internally or on the web)?

**Comment by elliotkendall** [comment]
This is for people running their own Auspice server that's being shared on the web, which is what my local user is doing

**Comment by tsibley** [comment]
@elliotkendall Our expectation I think is that there's always going to be something in front of `auspice view` (or `nextstrain view`) in the case when they're used for more permanent sharing (as opposed to primarily local interactive use). For example, I expect something has to be in front to meet your HTTPS requirement, since neither command supports TLS. Thus [my suggestion](https://discussion.nextstrain.org/t/post-nextstrain-results-on-the-public-website-securely/1029/4?u=trs) to add these security headers at the TLS-terminating reverse proxy layer (like Apache, nginx, etc). The app feels like the wrong level to be adding these headers since their presence/absence and appropriate values are specific to each individual deployment.

Is there something about your or your user's preferred deployment method or other constraints that makes this particularly difficult? If so, could you share more about the setup you're working with/desire (e.g. how is `auspice view` being run and managed, how is traffic getting to it, etc?)

**Comment by elliotkendall** [comment]
In this case, the "something" in front of Auspice is an Amazon ALB. That terminates TLS but doesn't support adding arbitrary headers. They could add Apache or nginx between Auspice and the ALB, but that seems like a lot of extra moving pieces just to insert a couple of headers.

I certainly understand your point about the app not being the right place to add these, though, especially since it doesn't natively support HTTPS.

**Comment by tsibley** [comment]
Hmm. I see. A self-contained reverse proxy like [Caddy](https://caddyserver.com/) would be a lot less moving pieces, but still an additional one. The minimal [Caddyfile](https://caddyserver.com/docs/caddyfile/concepts) might be something like:

```
# listen here, don't do HTTPS since ALB is doing that
http://localhost:4001 {
    # proxy to Auspice
    reverse_proxy http://localhost:4000
    header set Strict-Transport-Security …
}
```

and then just `caddy run`.

Another alternative to Auspice adding the headers itself (and thus having to expose a bunch of configuration knobs) would be to split up the [`run()` function in `auspice/cli/view.js`](https://github.com/nextstrain/auspice/blob/ea762db02ba111e11550c420df58a524bf21a49f/cli/view.js#L100-L155) into the bit that constructs and sets up the Express `app` object and the bit that binds to a socket to handle requests with `app`. That split would allow a small bit of custom JS to import from Auspice, construct the same `app` object, and set up additional middleware for security headers, etc. before listening for requests. Something like:

```js
const helmet = require("helmet");
const auspiceView = require("auspice/cli/view");

const app = auspiceView.createApp();
app.use(helmet());
app.listen(…);
```

then at least you don't have an additional HTTP server in the mix.

**Comment by tsibley** [comment]
Closing this issue as I don't think we're going to add security header support directly to Auspice.

Still, I think it would be worthwhile to split up Auspice's `app` creation from socket binding, as described above, to allow easier server customization such as adding these headers. Created as https://github.com/nextstrain/auspice/issues/1498.
