### ISSUE TITLE
Bioconda package not updated automatically: should be part of release

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1526]
It appears that new releases of Auspice are not automatically ending up on Bioconda.

We should automate this process or make it part of releases. How was this done in the past?

**Comment by corneliusroemer** [comment]
Last PR was this: https://github.com/bioconda/bioconda-recipes/pull/34900/files

**Comment by victorlin** [comment]
It was never automated as far as I know. Augur is automatic since Bioconda listens to PyPI for updates, but that doesn't happen for NPM which is where Auspice gets published. We need to update [DEV_DOCS.md](https://github.com/nextstrain/auspice/blob/1065e68b4007c93e072829ca223b2d01c0b4752d/DEV_DOCS.md#releases--versioning) with an extra step to manually make a PR in the bioconda repo.

**Comment by corneliusroemer** [comment]
It is possible to automate this more or less @victorlin 
We just need to download the package from npm, get the hash, then change the version string and hash in the recipe.yaml of bioconda and submit PR.
I've automated the hash part and PR creation for nextclade:
https://github.com/corneliusroemer/bioconda-recipes/blob/master/.github/workflows/BumpNextalignNextclade.yml

This can probably be done in a much nicer way :)
