### ISSUE TITLE
ENH: Split up deletions and substitutions in tooltip as deletions are overwhelming and uninformative

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1537]
### Context
When inspecting trees I often have issues with the way the presentation of deletions overwhelms the display.

### Description
Deletions are often very noisy on trees as we don't account for them properly when building a tree.

Yet they take up most space because they come in stretches that aren't compressed.

### Examples
So I end up with a result like this:

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/25161793/180436006-060564ab-3854-4cd2-8103-a90ee5cbf17d.png">

Where the needle (the two really important nuc substitutions) is really hard to find in the hay stack (long list of deletions).

It would be really great and quite high priority from my user perspective to make deletions less overwhelming.

This has actually impeded me for a while but I never had the idea of writing it up as an issue.

### Possible solution

@victorlin do you think this is something you could have a look at? There are a few things we could try here:
1. Simply split out substitutions and deletions (maybe easiest and quickest, maybe stopgap until we have)
2. Compress deletion stretches (and maybe separate them out, too)

**Comment by jameshadfield** [comment]
Related (private) slack thread [here](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1658492073338139). A summary of this:

Auspice already separates out deletions nicely (e.g. `G42-`) and groups them into runs. This problem is due to "undeletions" which are almost certainly a bioinformatics problem, albeit a hard one to fix. @corneliusroemer suggested to call these a “reversion of deletion to reference" which seems like a good solution. Some considerations:

1. We should group these together into runs, like we do with deletions.
2. They should not be listed in the "unique mutations", "Homoplasies" and "Reversions to root" categories
3. I don't think these should be restricted to reversion of deletion to reference - they should be any deletion to a base. Although this would obscure the interesting case when it's a base which differs from the ancestral node...
