### ISSUE TITLE
Diversity panel extends beyond genome end on 3' end

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1651]
### Current Behavior
The diversity panel x-axis extends beyond the 3' end of the genome.

e.g. for SARS-CoV-2 it goes roughly 150 bases beyond the 3' end at 29903 (Wuhan-Hu-1)
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/25161793/226488137-213792e7-e945-45b5-bd50-5bdadc400fd8.png">

This is asymmetric with the 5' end, where it starts at 0 and doesn't go negative:
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/25161793/226488298-9fb67969-46b1-40b5-98e9-11a81a52768d.png">

### Expected behavior
The position axis does not extend beyond the genome end (at least not more than a few bp)

The fact that the axis extends creates the user impression that the real genome is longer than it actually is, and that there is a lack of mutations - when in fact there can't be any mutations in this non-existent region.

See in our ncov builds: https://next.nextstrain.org/ncov/gisaid/global/1m?gmin=29677&l=unrooted&m=div

**Comment by jameshadfield** [comment]
Notes after a quick investigation into this. Relevant provided data (for nCoV):

```
“nuc”: { “start”: 1, “end”: 29903, ...
“N”: {  “start”: 28274,  “end”: 29533, ...
```

The lower scale (`xNav`) correctly sets and maintains a domain of `[0, 29903]`. The upper scale (`xMain`) starts with the same domain (assuming no URL query params). All ticks are managed by [d3's `axisBottom`](https://github.com/d3/d3-axis#axisBottom).

There's some space to the right of the lower scale which we can drag the selection box into, which is the cause of this bug. As we drag the selection to the RHS, [this function](https://github.com/nextstrain/auspice/blob/9b8b6843a0091cb12b470f6fc70a23a91976507d/src/components/entropy/entropyD3.js#L424-L440) calculates zoom coordinates as high as ~30,036. This has the flow-on effect of changing the domain of the upper scale ([here](https://github.com/nextstrain/auspice/blob/9b8b6843a0091cb12b470f6fc70a23a91976507d/src/components/entropy/entropyD3.js#L471-L472)), which is why d3 shows the tick at 30,000bp on the upper axis. The zoom selection can go further than the axis domain due to this code:

https://github.com/nextstrain/auspice/blob/9b8b6843a0091cb12b470f6fc70a23a91976507d/src/components/entropy/entropyD3.js#L484-L486

however removing the 20px of padding here introduces another problem (we can no longer drag the selection _far enough_), presumably the reason for this hack in the first place. I can mostly solve the bug by forcing the `zoomCoordinates` to never exceed the axis domain, but if we can work out why this hack is needed in `extent()` that would be the best.

**Comment by emmahodcroft** [comment]
I have a vague memory of also coming across this [that without some extra space you can't drag far enough] when I did some work on the diversity bar way back in the day.
