### ISSUE TITLE
Branch thicknesses not consistently applied

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#173]
![](http://i.giphy.com/26xBzLH4jU98m4Qnu.gif)

**Comment by jameshadfield** [comment]
On `move-to-redux` this problem manifests after clicking.
I believe this is related to the more general problem of how branchThicknesses are applied to the tree nodes.

**Comment by rneher** [comment]
this was largely due to branch thickness being referred to as `strokeWidth` in phylotree while the style that got set is `stroke-width`. It reverted to `d.strokeWidth` instead of `d['stroke-width']`. I changed it within phylotree to work properly. However, problems with `nextState.hover` and `state.branchThicknessVersion` remain
