### ISSUE TITLE
Limit x-axis by visible measurements

### ISSUE THREAD

**Issue by huddlej** [nextstrain/auspice#1814]
@rneher originally noted:

> In the measurement panel, some limits on the axis might be useful as well. We currently have -6 to 14 in some views (which is a million fold titer difference)

The following example from [the measurements panel paper dataset](https://nextstrain.org/community/blab/measurements-panel/flu/seasonal/h3n2/ha?p=grid) shows how the x-axis retains its original domain even after filtering to a single reference with a smaller range of measurement values. In this example, the x-axis domain should reflect the minimum and maximum std dev values at the lower and upper bounds.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/8b7e5e91-52fb-4203-bcb0-0fb98276808f">

Similarly, the raw measurements display for the same data should use the minimum and maximum measurement value plus/minus some small padding on the lower and upper bounds.

<img width="467" alt="image" src="https://github.com/user-attachments/assets/b836d334-eb93-4a7f-815a-88dc91c7b52f">

**Comment by joverlee521** [comment]
This should be straightforward to implement by changing which measurements get used to create the `xScale`. It currently uses _all_ measurements, but should be straightforward to switch out with `filteredMeasurements`

https://github.com/nextstrain/auspice/blob/dddc6c9b2c3f95ec3f9048d4681403e20bd7191b/src/components/measurements/index.js#L163

My initial gut feeling was this may significantly slow down transitions when applying filters to the measurements panel because the [`xScale` is memoized in the `svgData`](https://github.com/nextstrain/auspice/blob/dddc6c9b2c3f95ec3f9048d4681403e20bd7191b/src/components/measurements/index.js#L165-L174) and any changes to the [`svgData` will trigger a complete redraw of the SVG](https://github.com/nextstrain/auspice/blob/dddc6c9b2c3f95ec3f9048d4681403e20bd7191b/src/components/measurements/index.js#L218-L225). However, I'm remembering that the `svgData` already gets updated when we change the group-by and that transition is pretty smooth, so I'm not as worried about speed anymore.
