### ISSUE TITLE
When date range includes very-in-the-future dates, tree display is broken

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1892]
### Current Behavior

When looking at a tree that has very-in-the-future tips (year 4000 or so, obviously wrong, but Auspice should be able to handle nonetheless), tree panel of Auspice appears quite broken.

This is on Auspice v2.59.1

### How to reproduce
Steps to reproduce the current behavior:
1. Open cchf-l.json in auspice: [repro.zip](https://github.com/user-attachments/files/17662467/repro.zip)
2. Observe result

<img width="1918" alt="Brave Browser 2024-11-07 14 50 06" src="https://github.com/user-attachments/assets/e01aa5a2-3b0b-45a1-874c-5c67b968eb4e">

![2024-11-07 14 49 08](https://github.com/user-attachments/assets/66c60c05-9084-4ca9-9959-a0b958cd404f)

Note: I get the same behaviour also with auspice.us (which is on version 2.60.0)

Speculation about root cause: It seems that there's an incorrect time filter always on that shouldn't be on by default.

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify the getDefaultControlsState function to set a wider default date range and update the changeDateFilter action to handle extreme future dates.

I also created pull request: https://github.com/nextstrain/auspice/pull/1893


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by corneliusroemer** [comment]
@jameshadfield I'm sorry for all the issues I'm making 🙈 Could you have a look at this one too? You might have missed it due to my avalanche of issues.

**Comment by jameshadfield** [comment]
It's actually the root date (i.e. min date), not the date in the future, as JS by default maps 0-99CE to 1900-1999. (This tree's root node date is 17.632.)
