### ISSUE TITLE
Allow mouse scroll to zoom into map

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#260]
The implementation must not interfere with normal page scroll in the situation where the user wants to access information below the map (other panels, filters etc)

**Comment by tolot27** [comment]
Should this issue also address zooming in and out of the map using (e.g.) the mouse wheel? That would be a really cool feature I miss every day.

**Comment by tolot27** [comment]
I see that zooming via mouse wheel is disabled at https://github.com/nextstrain/auspice/blob/89108f725ef0d42fd1676600da8adadd7088ad79/src/components/map/map.js#L472. Why?

**Comment by tolot27** [comment]
BTW: Leaflet v1.6 is out and auspice still uses v1.2. I know, do not change a running system. But ...

**Comment by emmahodcroft** [comment]
Thanks for your comments @tolot27 ! We have disabled scroll to zoom because we found it really interfered with navigating the page - scrolling up and down to get to filters, etc. Too often you got 'caught' in zooming the map instead. Especially if you've just gotten the map exactly how you like it - this is really frustrating! 

However, we'd be happy for this to work better with some key combinations, like CTRL+Scroll or others!

**Comment by tolot27** [comment]
I've found the plugin [Leaflet.GestureHandling](https://github.com/elmarquis/Leaflet.GestureHandling) and try it. If it works, I can create a PR.

**Comment by jameshadfield** [comment]
@tolot27 that would be great (but as Emma said, the implementation has to play nice with page-scrolling!)

**Comment by tolot27** [comment]
@jameshadfield

>@tolot27 that would be great (but as Emma said, the implementation has to play nice with page-scrolling!)

That is exactly what the plugin provides. Did you see the screenshot or try the [sample](https://elmarquis.github.io/Leaflet.GestureHandling/examples/)?

**Comment by emmahodcroft** [comment]
Thanks for the link to the example! This looks and works great from my trials. Would be very happy for you to make a PR we can trial on Nextstrain. Thanks for looking into this!
