### ISSUE TITLE
resizing & moving of panels

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#278]
via user dragging on corner (or similar) to resize, or dragging on title to re-order

this is massive and won't be done anytime soon

we should make sketches (etc) before starting

**Comment by jameshadfield** [comment]
Closing as this is not currently planned

**Comment by joverlee521** [comment]
Leaving some thoughts here since James briefly mentioned panel re-ordering to me in a meeting on 2021-11-15:
1. We can allow custom default ordering by displaying panels in the order they are listed under `meta.panels` of the auspice JSON. Users can then define their custom panel order by editing their auspice config used in the `augur export` command. 
2. A way to do re-ordering without worrying about UI for now is to define panel order in the URL. Currently we only check if a panel is included in `query.d` but we can make the panels display in the listed order. (I think we would want this even if we added UI for the re-ordering.)
3. If drag-and-drop seems too much, we can add up/down arrows to the panel toggles in the "Panel Options" to change panel order. It seems intuitive to me that the panel toggles are listed in the order that the panels are displayed. Of course this would add some "clutter" to the control panel.
