### ISSUE TITLE
CORS error requesting s3 resources from client

### ISSUE THREAD

**Issue by colinmegill** [nextstrain/auspice#5]
I'm not sure if this is still a problem or not, but we should revisit now that we're structuring data fetching. This is the only reason we have routes in the dev server - to proxy resources to avoid CORS. In the dev server, the solution to #4 will look something like:

![image](https://cloud.githubusercontent.com/assets/1770265/17422683/07aafc0a-5a69-11e6-84e6-2c4b8d3a2b79.png)

But we could also construct this on the client and request to s3 directly if we solve the CORS issue, which will work in both dev and production. It will require getting localhost:4000 and nextstrain.org requests directly to s3 working.

**Comment by trvrb** [comment]
Can't we just ask for `/data/flu/h3n2/3y/tree.json` as in #4 and this will resolve to localhost:4000/data/flu/h3n2/3y/tree.json for dev and nextstrain.org//data/flu/h3n2/3y/tree.json for production? This requires local data for dev. However, this is a feature for me as it allows local builds to be visualized before uploading to production on S3.

There is also the goal of making this whole thing usable by other people. Local data will help with this.

**Comment by colinmegill** [comment]
Ah! Absolutely - if deploying a server is part of the plan that's great, didn't want this to be the only reason.

**Comment by trvrb** [comment]
Rather than requesting a URL like `nextstrain.org/flu/h3n2/3y/` and then routing this, what if the URL request was instead `nextstrain.org/?virus=flu&lineage=h3n2&resolution=3y`?

This would still request the default `index.html` and we could pull application state like in this [example](https://bl.ocks.org/vijithassar/raw/3518ea727b10e03d02a6c3fdd97d3b69/).

If we wanted to include shortcuts, we could just set up redirects that do things like redirect `nextstrain.org/flu/h3n2/3y/` to `nextstrain.org/?virus=flu&lineage=h3n2&resolution=3y`.

**Comment by colinmegill** [comment]
Yes, we can do query params rather than rest routes, definitely. It's less readable, which can be a feature, but with the number of things we'll want to control from the URL order independence is an asset long term, so, I'm for query params.
