### ISSUE TITLE
frequencies questions

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#505]
cc @huddlej @trvrb @rneher 

### Some relevant questions (add more as needed):
* Should normalisation be the default?
* How should residual error be dealt with? Currently if the raw frequency for a pivot is `<0.01` I collapse it to zero -- the alternative being to expand what is probably rounding / smoothing errors to what looks like 100% frequency. But this approach leads to sawtooth like displays:
![image](https://user-images.githubusercontent.com/8350992/36709906-61d318a6-1b2f-11e8-8ad1-c6456f955c82.png)

**Comment by trvrb** [comment]
@jameshadfield and @rneher: I thought a bit here and I came up with the following proposal:

1. We properly normalize tip frequencies in augur before exporting to auspice. With all tips shown the frequencies display will look like:

<img width="1080" alt="all" src="https://user-images.githubusercontent.com/1176109/36710506-457b10f6-1b33-11e8-907a-917f06a52e69.png">

2. We keep only "raw" frequencies and disable normalization. However, we dynamically rescale the y axis to fill the plot, so that zooming to a clade A1 would look like:

<img width="1085" alt="clade" src="https://user-images.githubusercontent.com/1176109/36710702-88e9b26a-1b34-11e8-95fb-21743d428d6e.png">

This should keep the app from getting into funny states and also keep the visualization well interpretable.

Even a very small clade ends up looking okay:

<img width="1084" alt="small_clade" src="https://user-images.githubusercontent.com/1176109/36710779-ec017590-1b34-11e8-8a18-6ec0ac8e74d8.png">

**Comment by rneher** [comment]
this looks good to me (even though I still don't fully understand the notion of a `tip frequency`)
