### ISSUE TITLE
What should be displayed when hovering on tips (tree) / demes (map)?

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#511]
### Questions
* Should the tip-click panel be removed (it currently shows clickable links which is nice, but I doubt it's ever used!) Tip-click could still filter to a single sequence like search does.
* from @rneher:
> nextflu's tooltips for branches can be quite handy (to look for mutations, titer drops, average ages, etc). currently nextstrain doesn't have this "on the fly" info. thoughts?
* from @trvrb:
> The Nextstrain spec was only showing colorBy attributes for the active colorBy. I think this the best way to do this as otherwise there are too many things in the tooltip, but tooltip labeling could be improved, should be "epitope mutations" like in the dropdown rather than "ep".

**Comment by jcw349** [comment]
We use the tip-click feature a lot, but I think if the panel is off to the side will be better.  

Also, tangentially related, right now when we click on the tips, it will toggle a specific location on the map, but the reverse (clicking on map demes) doesn't toggle the enlarged tips, it's only temporary as long as you're hovering.   It will be really useful for the tips to stay enlarged after clicking on the deme. We can use the mouse to hover over the enlarged tips to see more info about the selected deme/tips.

**Comment by victorlin** [comment]
Closing this in favor of https://github.com/nextstrain/auspice/issues/1729 which is specific to tree.

> when we hover over the demes, while the tips enlarge, they can sometimes be buried under other tips, can they be moved to top layer?

I think the approach here would be to select tips of interest with the filter feature so that other tips don't have a circle. If multiple selected tips are overlapping, there is a "Focus on Selected" toggle that adds extra space between selected tips. Feel free to open a new issue if this doesn't address your concerns.
