### ISSUE TITLE
Allow trees with just branch_lengths or just clock_lengths

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#649]
@jameshadfield ---

Currently, tree JSONs are required to have both `clock_length` and `branch_length`. However, if we do a light pass to directly visualize a tree from RAxML or from BEAST it will only have one or the other.

I encountered this when constructing a BEAST tutorial here: https://github.com/nextstrain/mers-beast-tutorial. I could add additional augur steps to have both `clock_length` and `branch_length`, but the simplest pass does not include both. I believe that auspice should be able to work with this sort of data.

You can see the resulting JSONs here: https://github.com/nextstrain/mers-beast-tutorial/tree/master/auspice and notice that they currently crash auspice: https://nextstrain.org/community/nextstrain/mers-beast-tutorial

This has just `div` and `branch_length`. I need to fix `augur refine` to properly call these `num_date` and `clock_length`, but the issue still stands.

I would propose greying out the option TIME or DIVERGENCE that doesn't apply to a particular dataset.

**Comment by jameshadfield** [comment]
Agreed. This is part of the JSON 2.0 plan (the schemas for 2.0 do not require num_date or div) 👍

**Comment by jameshadfield** [comment]
I believe @emmahodcroft is playing around with the implementation of this 👍

**Comment by emmahodcroft** [comment]
@jameshadfield  and @trvrb - 
I've created a branch (`no_date`) which should now handle cases where there is `branch_length` and `div` but no date information. I also created a branch in `augur` (not pushed yet) which modifies `refine` so that if date information on the tips is present (but `--treetime` option not run, for example, so no dates on internal nodes) this is included in the `branch_lengths.json` file. (In theory this could then be visible in auspice in some manner - for example on mouse-over.)

`no_date` works by looking at the root node to see if it has `num_date`, and if not, setting a new variable, `displayDates`, to false. This keeps the default dates behind-the-scenes (seemed the easiest work-around), ensures all nodes will be visible regardless of 'date' (or lack thereof), forces the default view to be `div`, removes the date-slider, 'Time' option (in 'Branch Length'), and animation options from the controls, and removes the 'play/reset' buttons from the map. 

This seems to work with the files you provided Trevor, and some I mocked up myself. I still need to ensure this carries over to 'treeToo' if visible (next step).

If there are any example files that have date only (inverse of the above) this would be useful for me to start tackling the next bit - I can mock them up of course but if they've come from something 'real' it helps ensure I'm making the right assumptions.

**Comment by trvrb** [comment]
@emmahodcroft ---

This is fantastic. I demoed with the MERS example here: https://github.com/nextstrain/mers-beast-tutorial/tree/master/auspice. Works really well. Two small notes:

* We should disable "clock" layout as well. Without dates, this is broken.
* We should remove "sampled between Jan 0002 and -100000" in the info text under title.

I believe that @jameshadfield now has a date only MERS JSON that he could share.

**Comment by jameshadfield** [comment]
@emmahodcroft i've got some from-BEAST date only JSONs we can look at this week 👍

**Comment by emmahodcroft** [comment]
@trvrb - Thank you for spotting those two things! I've added a couple of changes that should fix them. @jameshadfield I'm happy to start looking at date-only files whenever is good!

**Comment by trvrb** [comment]
@emmahodcroft --- Nice! I think `no_date` can be PRed.

**Comment by emmahodcroft** [comment]
@trvrb - I had a chat with @jameshadfield about this this afternoon. I started working on supporting lack-of-dates having completely forgotten this issue, and thus that the inverse (date only) should be supported too - so my `displayDates` is a binary trait. James suggested, and I agree, that probably a better way forward would be to make this able to hold 3 values to represent 'both,' 'date only,' and 'div only.' (Inspired by @rneher's suggestion for the node visibility.) 

Given that, would it be better to PR this as it stands and then make those changes, or do it all here first?

**Comment by trvrb** [comment]
@emmahodcroft --- I like this suggestion (for three values, like node vis). One development strategy would be to change the current `displayDates` to be `branchLengthsToDisplay` (in analogy to existing `panelsToDisplay` and have this map to `divAndDate` or `divOnly`. You can then add a `dateOnly` option on top of this as a separate PR.

Node vis was shortened to an integer for performance reasons. Here, I'd keep as string.

**Comment by emmahodcroft** [comment]
@trvrb  - I've made this change and created PR [670](https://github.com/nextstrain/auspice/pull/670) - I'll start expanding this to date-only trees.

**Comment by trvrb** [comment]
That's fantastic. I'll take a look @emmahodcroft.

**Comment by jameshadfield** [comment]
Closed by @emmahodcroft in #670
