### ISSUE TITLE
v2 JSON schema for zika tutorial 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/auspice#734]
These bugs can be seen when viewing v2 JSON for the zika tutorial. 
- The "Filter by Authors" lists the unique author keys rather than the author names.

<img width="1117" alt="Screen Shot 2019-07-03 at 1 44 26 PM" src="https://user-images.githubusercontent.com/40774762/60623954-e55a4900-9d98-11e9-9139-bf3e16edbe3c.png">

- Nodes from the same author all display the same URL even though the URL is specific for one accession

<img width="553" alt="Screen Shot 2019-07-03 at 1 51 27 PM" src="https://user-images.githubusercontent.com/40774762/60624266-b1335800-9d99-11e9-9033-259d295a4bd9.png">

**Comment by emmahodcroft** [comment]
Just catching up on v2 stuff and I have spotted what seem to be differences in what we expect of URLs here and how they are working.

As I understand, URLs passed in become the URL for the accession number. So it seems they do not need to be displayed in a separate field in the pop-up? Also, this then causes a lot of warnings because of 'contradictory author information' because the accession-number URLs differ (of course they do).

How do we actually want the URL field to operate? What should be here? It seems this isn't really pinned down, hence seeming conflict in how it's used/checked.

**Comment by jameshadfield** [comment]
Closed by https://github.com/nextstrain/auspice/pull/741 and https://github.com/nextstrain/augur/pull/315
