### ISSUE TITLE
Title of map panel: "Transmissions" -> "Geographic distribution"

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#743]
For many builds, we don't infer ancestral states. In this case, there are no transmission lines to be displayed and the title of the panel is misleading. I would prefer "Geographic distribution" similar.

**Comment by trvrb** [comment]
Historically, I had wanted the "Transmissions" panel name, because I had thought to make this abstracted from geography. Ie you could place demes in a circle or according to a spring embedding. And in this case you could show things like camel/human transitions in MERS or between genotype transitions in flu. Obviously, this never happened.

I do think I'd prefer a slightly shorter name than "Geographic distribution". How about just "Geography"?

<img width="1098" alt="geography" src="https://user-images.githubusercontent.com/1176109/61472986-5c1b4880-a93a-11e9-9647-be84786412b1.png">

(I also tried "Tree" and "Mao" for simplicity, but this looked too informal.)

**Comment by rneher** [comment]
happy with that. But 'Mao'? 'Lenin'?

**Comment by jameshadfield** [comment]
Why not both? 😉 

Screenshots of toggling geo-resolution in WNV (transmissions only inferred for "country") on branch [map-title](https://github.com/nextstrain/auspice/tree/map-title)

![image](https://user-images.githubusercontent.com/8350992/61496504-758ec400-aa10-11e9-8ffe-7b791ba69d81.png)

![image](https://user-images.githubusercontent.com/8350992/61496508-7d4e6880-aa10-11e9-9b84-ba7e7f24cef3.png)

**Comment by rneher** [comment]
great!

**Comment by emmahodcroft** [comment]
>Why not both? 😉

Where are [gifs](https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif) in github when you need them!
