### ISSUE TITLE
`num_date` missing -> crash

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#745]
I  am working with a very bare-bones json (export v2) and it makes auspice crash bc num_date is missing

![image](https://user-images.githubusercontent.com/8379168/61519141-740ecd00-aa0b-11e9-978f-a468cb2b204d.png)

**Comment by jameshadfield** [comment]
Huh. It _shouldn't_ because div-only trees are/were fine. Will fix.

**Comment by emmahodcroft** [comment]
### Bug 1:

Hmmm... I think this is because in `export v2` we do not check whether the tree has date information - it is assumed. 
See line [#184](https://github.com/nextstrain/augur/blob/33721adb5cd60c9f3411e2189c11c55a1e31591a/augur/export_v2.py#L184)

This is reflected in your JSON @rneher, as under `colorings` you have `num_date`.

So, it's breaking in a different part than our previous fix to detect whether date information is there or not - this is actually earlier. Since there's no 'country' (default colorby), it's cycling through the other colorbys given (from export) - and breaks when it looks into `num_date` (as passed by export).

**Fix**: `export v2` needs to check for date info and only add as a colorby if it exists.

-------

Richard just said that even if you get rid of this in the JSON it still errors. 

### Bug 2:

I believe this was introduced in [this commit](https://github.com/nextstrain/auspice/commit/969a58fb92a31c3b6cbed6dc73d680a636d50235), which is replacing the old style `node.attr.num_date` with `node.num_date.value`. 

The big difference here is that `node.attr.num_date` had the value if present and was undefined if not. So, you could pass it around and check whenever you like whether it was undefined. 

With `node.num_date.value` - `node.num_date` holds `value` and `confidence` (list of 2) if dates are present, and is undefined if not. If it's undefined, you get errors anytime you try to access `value`!

This can be seen in things like:
_Old code_:
`const nodeDate = node.attr.num_date;`
Then later we check whether `!nodeDate` and break (or whether it's > or < something, if it has value)

_New code_:
`const nodeDate = node.num_date.value;`
We can try to check later if `!nodeDate` - but we have already errored by tracking to access `value` from the undefined `node.num_date`...

**Fix**: Need to chase these replacements through relevant files and update them so we don't try to access `value` before we check if undefined.

**Comment by emmahodcroft** [comment]
I pushed a PR for the second bug, and I think I've figured out the first too - but going Rhine swimming now - will push later! 🏊‍♀ 😎

**Comment by emmahodcroft** [comment]
Should work now with fixes above...!

**Comment by emmahodcroft** [comment]
@rneher @jameshadfield Is this resolved now - can we close?
