### ISSUE TITLE
Remove `_source` server-injected JSON property

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#783]
Over various iterations of the JSON sent to the client (not the JSON produced by augur; see here for background) we have had 3 keys injected in various guises. As we move to having the dataset JSONs handed directly to the client (no server modifications) we need alternative solutions.

One of these injected keys was `_source`

The "source" was largely a historical legacy and is only used by the dataset-display sidebar part of auspice. This is how auspice knows to display the github URL in the sidebar as opposed to a listing of available datasets.

~Proposed solution: Write logic in auspice to decide this from the URL. Allow build-time customisations to modify this.~

### Solution:
Use the available dataset JSON to define a (optional) build URL key for each dataset which auspice can display. This will allow us to recreate the community dataset behavior which currently exists, while also allowing them to list other available datasets (see https://github.com/nextstrain/nextstrain.org/issues/23). This is similar in spirit to how we now define available second tree datasets.

For example, "/charon/getAvailable?prefix=/community/pauloluniyi/lassa/l" should return something along the lines of
```
[
    request: "community/pauloluniyi/lassa/l",
    buildUrl: "https://github.com/pauloluniyi/lassa
],
[
    request: "community/pauloluniyi/lassa/s",
    buildUrl: "https://github.com/pauloluniyi/lassa
]
```
which will render in auspice as both a link to the github URL and a dropdown of available datasets.

**Comment by jameshadfield** [comment]
I can implement this next week if needed.

**Comment by jameshadfield** [comment]
4e963863e9813ecf42ecef3dbedc791e6d1505a4

**Comment by tsibley** [comment]
It seems like it'd be nice to have this information optionally embedded in the Auspice JSON metadata files (`*_meta.json` for v1 and the "main" `*.json` for v2).

I realize right now we need a retroactive solution for existing community builds which don't have this info in them, and that's fine. But thinking forward, it'd be nice to provide build links for all our datasets. Thinking about how to do that, nextstrain.org's `/charon/getAvailable` shouldn't have to hardcode where the builds are for core, staging, and private data sources (because the build is separate from the dataset storage, unlike most of the community builds).
