### ISSUE TITLE
info boxes too big

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#842]
when lots of metadata fields are available, tip info boxes get quite large -- sometimes large enough that there is no space left to 'click outside the box' to get rid of it.

 * should we have a way to restrict data shown there? if so, at the level of the `export` and in the json, or dynamically via a UI
 * limit the size of the box? make it scrollable? separate close button...

**Comment by trvrb** [comment]
I generally like the idea of a close button on the modals (while still keeping the click outside behavior). The download modal does scroll, so that could be a target. Also, we might think about centering the tip modal on the screen (like the download data modal), in part to give more real estate. The map and diversity panels are pretty uninteresting with one tip selected anyway.

**Comment by jameshadfield** [comment]
We can definitely add a `x` button to the modal right now so that this isn't problematic in the short term. Let me know & I can do this ASAP.

More generally, the tip modal box isn't ideal, especially with narratives. We want some way of seeing this information without obscuring the tree. Reloading a tree with a tip selected also doesn't bring up this modal (e.g. https://nextstrain.org/zika?s=Angola/2017/PoHuZV634959) -- this is a bug which is somewhat helpful for narratives.

**Comment by jameshadfield** [comment]
Closed by #862 -- thanks @emmahodcroft 🎉
