### ISSUE TITLE
Clicking "Leave the narrative & explore the data yourself" leads to an incomplete page

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/auspice#871]
Repro:
 - Go to the latest situation report on 2019-ncov, currently at https://nextstrain.org/narratives/ncov/sit-rep/2020-01-30
 - Scroll to the very last page
 - Click "Leave the narrative & explore the data yourself"
 - You will be redirected to the latest https://nextstrain.org/ncov results, however, the page does not show either phylogeny tree or map and the sidebar seems rather empty
 - Refresh the page. The page is now complete, as expected.

I think this is a bug and the complete page with phylogeny tree and map should be shown from the beginning.

**Comment by tsibley** [comment]
Thanks for the report! I also noticed this same bug yesterday. It appears to happen for any narrative page that uses a Markdown panel instead of a standard Nextstrain panel (map, tree, etc). I agree this is a bug and that it would be better to show the default Nextstrain panels for the dataset when leaving the narrative from a Markdown page.

**Comment by emmahodcroft** [comment]
I can confirm this is true when running the latest `auspice` locally - when 'exploring' from markdown pages rather than tree/map pages.

**Comment by jameshadfield** [comment]
This is because the only "panels-to-show" is the markdown panel, which can't be displayed outside of narrative mode, so we end up with nothing displayed. It should reset to the "default" view, which we do keep a copy of (this is set via the dataset JSON).

Separately, when viewing a narrative page with main-page-markdown shown, we should remove the "Explore the data" button.
