### ISSUE TITLE
Narratives pagination ignores page url param

### ISSUE THREAD

**Issue by ivan-aksamentov** [nextstrain/auspice#873]
Navigation to, let's say, https://nextstrain.org/narratives/ncov/sit-rep/2020-01-30?n=8 leads to the first page, not 8th, even thought the url param is preserved.

I would consider this a UX bug, because most users expect pagination state to be retained between navigations, after using a bookmark etc.

This is typically implemented in client-side routing. For example, in react-router, one may use 
[`withRouter`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md#withrouter) HOC or, better, [`useParams`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md#useparams) hook.

**Comment by emmahodcroft** [comment]
Hey Ivan - thanks for all the hard work! I know this bug was fixed by James last night - possibly some of the other ones too. They are in the latest version of `auspice` if you run from the source here, but I'm not sure it's been deployed on the nextstrain website yet, which might be why these aren't showing up there. 
@trvrb @jameshadfield Is it that the latest version isn't yet deployed, or updated? As definitely in testing all day, the direct linking is working.

**Comment by ivan-aksamentov** [comment]
@emmahodcroft Cool, thanks for heads up!
