### ISSUE TITLE
Zoomed in Switch to 'Div' view for Flat Polytomy Gets Weird

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#901]
If on 'Time' view, zoom in to something that's a 'flat polytomy' in 'Div' view, then switch to 'Div' view, you get super weird stuff - branches should be flat (no branch lengths, as shown), no idea what branch labels are:

![image](https://user-images.githubusercontent.com/14290674/75037858-6c3d6c80-54b5-11ea-84d0-105b1cd6f4f5.png)

To replicate:
On [nextstrain.org/ncov](https://nextstrain.org/ncov) in default 'Time' view, click on the top cluster of ~8 descendants.
While zoomed in, switch to 'Div' view. 

Depending on what's showing, and what version has just run, you seem to get some differences in the axes labels:
![image](https://user-images.githubusercontent.com/14290674/75037978-adce1780-54b5-11ea-8dd6-7d63376b0e00.png)

This probably isn't high priority, but wanted to document.
Using 'Reset View' seems to restore normalcy.

**Comment by jameshadfield** [comment]
Looking into this now. Augur does export a certain amount of divergence for those branches -- tiny amounts like `3.0794047756782606e-12` -- and because the overall view is limited to ~ 3 * tiny_amounts, then auspice spaces this out like in the screenshot. Should be able to set a minimum divergence domain to prevent this.
