### ISSUE TITLE
clade labels suppress amino acid labels

### ISSUE THREAD

**Issue by rneher** [nextstrain/auspice#905]
When labeling branches with amino acids, these labels don't show on branches with clade labels. see branches at which clades changes. Most have aa changes, but they don't show. 

https://nextstrain.org/flu/seasonal/h1n1pdm/ha/6y?branchLabel=aa

**Comment by jameshadfield** [comment]
This issue is a bit complicated, so i'll try to explain what's going on:

Firstly, there is a difference _in the JSON_ between `aa` labels and AA mutations. Auspice is designed to display the former, but not the latter. Augur isn't exporting the labels correctly, e.g. in h1n1pdm / ha / 6y.

```json
                          "labels": {
                            "clade": "6b"
                          },
                          "mutations": {
                            "HA1": [
                              "K163Q",
                              "A256T"
                            ],
```
Although I can't immediately see the error in [the augur code](https://github.com/nextstrain/augur/blob/master/augur/export_v2.py#L527)

---

Secondly, there is an issue with auspice, which I've fixed (PR soon). We currently have [this code](https://github.com/nextstrain/auspice/blob/master/src/components/tree/phyloTree/labels.js#L74) to decide what labels to display, as to display them all isn't good:

![image](https://user-images.githubusercontent.com/8350992/75291403-02430f80-5887-11ea-9da3-4dfbec180785.png)

As we add more labels other than just clade / aa, this is not ideal. I'll create a PR ASAP to propose we:
(a) Display all label values by default, unless the labeling is `aa` (see screenshot above)
(b) for `aa` labels, display them if the branch has any other labels, or if it meets the current threshold.
