### ISSUE TITLE
RFC: Live editing of narratives

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#957]
This issue is a request for comments relating to functionality that we would like in auspice (or perhaps it's better as part of nextstrain.org?). For a background to narratives please see https://nextstrain.github.io/auspice/narratives/how-to-write. 

### The current situation
Currently to create a narrative you must take one of two paths:
1.  install auspice locally, download the dataset you wish to write a narrative for, create a markdown file, edit the markdown file whilst viewing the result in auspice locally, then upload the markdown file when you wish to publish it. 
2. Same as 1, but don't test locally and hope that it Just Works in nextstrain when you upload it!

It would be great to have a live-editing functionality whereby you could essentially write the markdown in the browser and have it displayed on-the-fly. There would then be some functionality to either (a) download the markdown file when done and/or (b) publish it (currently publishing means uploading to a GitHub repo). 

In order to start discussion I've created these two (preliminary!) mocks for how something could look:

![narratives_p1](https://user-images.githubusercontent.com/8350992/76820706-c3deb600-6870-11ea-9f2f-98a556825b8a.png)

![narratives_p2](https://user-images.githubusercontent.com/8350992/76820708-c4774c80-6870-11ea-9b92-fe83e5120554.png)

### Discussion points:

* It's not clear how simple it will be to programmatically import `auspice` to view the current markdown slide and update it as it changes. I didn't build auspice with this in mind! There may be different solutions here.
* @cassiawag hopefully this will really help with translations. What are some of the points needed to be taken into consideration for this? I'm imagining (a) starting with the content "filled in" from a previous markdown file and (b) publishing to a GitHub branch / fork...
* @enjalot you mentioned you have experience here, so I'm tagging you in the hope you can guide some of this!

**Comment by enjalot** [comment]
I've had good experience using [CodeMirror](https://codemirror.net/) in other projects as a markdown IDE.
It sounds like the pieces are all there, but as you note there may be some considerations around live-updating the auspice view. I'll see if I can dig into the code and understand the flow.

Some other things to consider:
* maintaining temporary state while editing, so that browser crashes/accidental navigating away doesn't destroy work (could use localstorage or indexdb for this)
* different editing modes: split screen, vs edit mode vs full preview
* another thought: the markdown and the query could be treated as separate editing modes, so that you can iterate on how your query will render full screen, but when you edit markdown you are seeing the output update live (since it will always be displayed narrowly). I may need to sketch this to communicate the idea better.

**Comment by cassiawag** [comment]
In addition to the considerations you mentioned, let me add this:
- access for multiple people to live editing the same markdown file at the same time. With translations, people have accidentally overwritten each other or had massive merge conflicts because they were both working on the same section at the same time. 

Will keeping thinking on this and re-comment here if more comes up.

**Comment by lukas-eu** [comment]
This tool might be quite helpful here to create a simple, less integrated solution: https://hackmd.io/#
It is an online md editor that comes with autosave, collaboration, and github integration.

**Comment by hydrosquall** [comment]
Some resources around how live-editing collaboration is implemented from another community project considering adding this capability:

https://github.com/processing/p5.js-web-editor/issues/1337#issuecomment-604934466

**Comment by jameshadfield** [comment]
I made a (very basic) start to this functionality in #1117 which implements the machinery for changing pages and editing the narratives content in the browser. There's a large list of future additions in that PR. 

If there's any takers to carry on this work, or just add small bits & pieces into that PR, then please jump in, as unfortunately I don't have the time to work on this feature at the moment.

**Comment by eharkins** [comment]
@jameshadfield should we close given the move of #1117 over to https://github.com/nextstrain/auctor?
