### ISSUE TITLE
[i18n] Translate Auspice to Japanese

### ISSUE THREAD

**Issue by crwilcox** [nextstrain/auspice#981]
Following the guide at:
https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n

**Comment by yuryu** [comment]
I'm working on this but I have issues around word orders in Japanese.
For example,

```
  "Showing {{x}} of {{y}} genomes": "Showing {{x}} of {{y}} genomes",
  "sampled between {{from}} and {{to}}": "sampled between {{from}} and {{to}}",
  "and comprising": "and comprising",
  "comprising": "comprising",
```

has the verb "Showing" in the beginning. In Japanese, the verb would be placed at the end. So the natural word order would be something like "{{from}} and {{to}} between sampled {{x}} of {{y}} genomes comprising ... showing." Currently, the template doesn't allow this change.

I'll try to respect the current granularity for now. I think we want to make these phrases bigger to contain entire sentences rather than clauses.

**Comment by yuryu** [comment]
Yes, they are numbers and dates and I can keep them. But there are some texts that are added outside the templates, such as (from https://github.com/nextstrain/auspice/blob/master/src/components/info/info.js#L91)


```js
  const prefix = branchLengthsToDisplay !== "divOnly" ? t("and comprising") : t("comprising");
  const filterText = arrayToSentence(filterTextArr, {prefix: prefix, capatalise: false});
  if (filterText.length) {
    summary += ` ${filterText}`;
  } else {
    summary += ". ";
  }
```

In this case, the code assumes that you can add ```filterText``` after the template and there's currently no way to control it.

**Comment by crwilcox** [comment]
Let me submit a PR to correct that. I think we could calculate those adds and allow one entry to address it.

**Comment by jameshadfield** [comment]
@yuryu thanks for identifying this - current auspice master should now work 🤞 - please let us know if there are any other word-order issues!
